TARGET		:= Prototype
TITLE		:= PROTOTYPE

PKG_CONFIG = arm-vita-eabi-pkg-config
SDL_LIBS := $(shell $(PKG_CONFIG) --static --libs SDL2_mixer SDL2_net)

LIBS	:= $(SDL_LIBS) -lvitaGL -lvitashark -lmathneon -lSceShaccCgExt -lSceShaccCg_stub \
	-lvorbisfile -lvorbis -logg -lpthread -lSceAudio_stub -lSceAudioIn_stub -lSceHid_stub -lz -lScePower_stub \
	-lmpg123 -lmikmod -lFLAC -ltaihen_stub -lSceNetCtl_stub \
	-lSceAppMgr_stub -lSceCommonDialog_stub -lSceCtrl_stub -lSceGxm_stub -lSceMotion_stub -lSceNet_stub \
	-lSceTouch_stub -lSceSysmodule_stub -lSceKernelDmacMgr_stub -lSceDisplay_stub -lSceIme_stub

OBJS = AnimGenerator.o Font.o Serpent.o Beam.o FrontEnd.o SolarFlare.o Boss.o Game.o Sound.o BrainBoss.o Generator.o SpaceTrash.o BrainCell.o Geo2D.o Sperm.o BreakScenery.o Geo2D_Draw.o Sprite.o Bug.o HUD.o SpriteEffect.o Bullet.o LadyBird.o SpriteSheet.o Button.o Log.o StarBurst.o CheckPoint.o Map.o stdafx.o Debris.o MidBoss.o SuperTurret.o Demo.o Orb.o Timer.o Editor_Anims.o Player.o TriggerSlowDown.o Editor.o PostEffects.o TriggerSpeedUp.o Editor_EntityProperties.o PowerDroid.o Turret.o Engine.o PowerUp.o UTIL_bitop.o Engine_Generators.o Profiler.o UTIL_Fade.o Entity.o ProtoType.o UTIL_Misc.o Explosion.o RandExplosion.o UTIL_openGL.o Fighter.o Rhino.o UTIL_SDL.o firebug.o Rocket.o Fire.o Serializer.o

PREFIX  = arm-vita-eabi
CC      = $(PREFIX)-gcc
CXX      = $(PREFIX)-g++
CFLAGS  = -Wl,-q,--wrap,fopen,--wrap,stat,--wrap,opendir,--wrap,remove \
	-O3 -g -fno-optimize-sibling-calls -I$(VITASDK)/arm-vita-eabi/include/SDL2 -DNO_FMOD -DUSE_SDL2 -w
CXXFLAGS  = $(CFLAGS) -fno-exceptions -std=gnu++11
ASFLAGS = $(CFLAGS)

all: $(TARGET).vpk

$(TARGET).vpk: $(TARGET).velf
	vita-make-fself -c -s $< eboot.bin
	vita-mksfoex -s TITLE_ID=$(TITLE) -d ATTRIBUTE2=12 "$(TARGET)" param.sfo
	vita-pack-vpk -s param.sfo -b eboot.bin $@ \
		-a livearea/icon0.png=sce_sys/icon0.png \
		-a livearea/bg0.png=sce_sys/livearea/contents/bg0.png \
		-a livearea/startup.png=sce_sys/livearea/contents/startup.png \
		-a livearea/template.xml=sce_sys/livearea/contents/template.xml
	
%.velf: %.elf
	cp $< $<.unstripped.elf
	$(PREFIX)-strip -g $<
	vita-elf-create $< $@

$(TARGET).elf: $(OBJS)
	$(CXX) $(CXXFLAGS) $^ $(LIBS) -o $@

clean:
	@rm -rf $(TARGET).velf $(TARGET).elf $(OBJS) $(TARGET).elf.unstripped.elf $(TARGET).vpk